#!/usr/bin/bash

declare -a COMMANDS=(foo bar usage)

_complete() {
    local line="${1#* }"
    for c in ${COMMANDS[@]}; do
        [[ $c =~ ^$line ]] && echo $c
    done
}

declare -A tests
tests["cmd fo"]=foo
tests["cmd foo"]=foo
tests["cmd foo "]=foo
tests["cmd u"]=usage
tests["cmd us"]=usage

for t in "${!tests[@]}"; do
    [[ $(_complete "$t") = ${tests[$t]} ]] || echo "fail: '$t'"
done
