#!/bin/bash

declare B=$'\033[1m' X=$'\033[0m'
[[ ! -t 1 ]] && B= && X=

DIR="$HOME/.local/share/iam"
[[ -d "$DIR" ]] || mkdir -p "$DIR" &>/dev/null

declare -A modes
modes[muted]='🔇'
modes[away]='🐟'
modes[working]='☕'
modes[chatting]='💬'
modes[ranting]='🤬'
modes[recording]='🎬'
modes[partying]='🎉'
modes[gaming]='🕹️ '

x_modes() {
  for i in "${!modes[@]}"; do
    echo "${modes[$i]} ${B}${i^}$X"
  done
}

_basic() {
  local message="$*"
  [[ -z "$message" ]] && read -r message -p "Message: "
  t "${modes[$CMD]} $CMD $message" 2>/dev/null
  echo "$CMD" > "$DIR/mode"
}

x_working() { _basic "$@"; }
x_chatting() { _basic "$@"; }
x_ranting() { _basic "$@"; }
x_partying() { _basic "$@"; }
x_recording() { _basic "$@"; }
x_gaming() { _basic "$@"; }

x_away() {
  local message="$*"
  [[ -z "$message" ]] && message="since $(date +%FT%T%z)"
  away="🐟 away $message"
  t "$away" 2>/dev/null
  pomo stop
  fishies
}

x_muted() { touch "$DIR/muted"; }
x_speaking() { rm "$DIR/muted"; }
x_mode() {
  [[ -e "$DIR/mode" ]] || return 1
  echo -n "$(<"$DIR/mode")"
  [[ -e "$DIR/muted" ]] && echo -n " muted"
  echo
}

#--------------------- completion and delegation --------------------

while IFS= read -r line; do
    [[ $line =~ ^declare\ -f\ x_ ]] || continue
    COMMANDS+=( "${line##declare -f x_}" )
done < <(declare -F)

if [[ -n $COMP_LINE ]]; then
    line=${COMP_LINE#* }
    for c in "${COMMANDS[@]}"; do
        [[ ${c:0:${#line}} == "${line,,}" ]] && echo "$c"
    done
    exit
fi

EXE="${0##*/}"
for c in "${COMMANDS[@]}"; do
    if [[ $c == "$EXE" ]]; then
        "x_$EXE" "$@"
        exit $?
    fi
done

CMD="$1"; shift
for c in "${COMMANDS[@]}"; do
    if [[ $c == "$CMD" ]]; then
        "x_$CMD" "$@"
        exit $?
    fi
done

