#!/usr/bin/bash

declare clear=$'\033[2J'
declare top=$'\033[H'

marquee() {
  local epoch=$(date -u +%s)
  if (( epoch%20 < 10 ));then
    echo "$(topic)  $(pomo)"
  else
    echo "$(cronoji) $(date +"%A, %B %-e, %Y, %-l:%M%P %Z%0z")  $(pomo)"
  fi
}

marquee "$@"

if [[ -t 1 ]];then
  trap "setterm --cursor on; echo $clear; exit; trap -- - SIGINT SIGTERM" SIGTERM SIGINT
  setterm --cursor off
  while true; do
    echo -n "$clear$top"
    marquee "$@"
    sleep 1
  done
fi
