cat.509670=Science & Technology
cat.29595=Dota 2
cat.509658=Just Chatting
cat.115977=The Witcher 3: Wild Hunt
cat.1469308723=Software and Game Development
cat.16676=Team Fortress 2
cat.493575=SHENZHEN I/O
cat.272263131=Animals, Aquariums, and Zoos
cat.509671=Fitness & Health
cat.26936=Music
cat.509660=Art
cat.515214=Politics
cat.417752=Talk Shows & Podcasts
cat.498592=I'm Only Sleeping
cat.509672=Travel & Outdoors
cat.509673=Makers & Crafting
tag.linux=15f4833a-1691-4cc1-a4a5-020d130ac94d
tag.ama=67259b26-ff83-444e-9d3c-faab390df16f
tag.coworking=0739209c-9ef5-4ae0-997c-ccbeb864ca61
tag.business=c38aeb6e-e8c7-452a-88e1-a3ed62c2e846
tag.cooperative=63e83904-a70b-4709-b963-a37a105d9932
tag.programming=a51f1e4e-257b-4bd0-90c7-189c3efbf917
tag.educational=cea7bc0c-75a5-4446-8743-6db031b71550
tag.writing=81975ba3-5c53-41f8-b614-ce5b3193955a
tag.editing=325a32c7-7b8e-48f8-b4fa-10875f18bb6d
tag.cozy=adc4a830-07f5-457b-95e5-5ab6cc1f9af3
tag.skateboarding=fd6df368-7e76-4868-b9e9-b4f7cecc2f35
tag.cycling=d5713b1e-c796-4bdc-88e2-93c49ce31136
tag.animation=e3a6b378-232b-4ec2-9a82-86b72851e09a
tag.evil=0cef8341-8c67-481f-95a8-325932a6699c
tag.good=ee1daaae-116a-44d6-9f40-09322caf3181
tag.endurance=3379ff9c-3c15-4bef-bfb8-2085cd196062
tag.engineering=dff0aca6-52fe-4cc4-a93a-194852b522f0 
tag.backseating=96b6073f-450d-4248-8ed4-988e28f3f759
tag.balance=8315b8d6-9837-4218-9bc1-3c0a3e5bb41d
tag.100=e659959d-392f-44c5-83a5-fb959cdbaccc
tag.achievements=27937cec-5cfc-4f56-b1d3-f6e1d67735e2
tag.acoustic=eea4d45b-52e0-4a16-b0df-64f4c55bc716
tag.behindscenes=26befb18-4ddc-41c1-8d39-ffeada297428
tag.bodypositive=150f13a5-b1ce-4e85-a61f-7cfed2e2e08c
tag.chatty=afc8211a-8eee-48b8-9e18-212f22f657db
tag.chill=81e9d348-82e5-4c4f-a140-d2b3779b912d
tag.explore=a4fac2cc-7cd4-44a6-b620-178182389a5b
tag.filming=812a0088-22a9-4944-bb27-af0fa37b6085
tag.firstplay=d0976a7e-26a7-4a48-9225-c522808540f2
tag.gamedev=f588bd74-e496-4d11-9169-3597f38a5d25
tag.softdev=6f86127d-6051-4a38-94bb-f7b475dde109
tag.webdev=c23ce252-cf78-4b98-8c11-8769801aaf3a
tag.graphicdesign=0930677c-dd75-424d-9190-b779f3d1c136
tag.hiking=2a824c85-8c64-4a62-9532-84a50633c6fc
tag.interviews=c833db83-32d0-4026-b3df-637ccf7899fa
tag.play=8ba227ca-073c-46a7-b3cc-193e52c5ab4d
tag.playwith=ac763b17-7bea-4632-9eb4-d106689ff409
tag.leveling=6433db3e-37a7-4590-915a-7c0949a4ac89
tag.vlogging=7a3d677a-1e09-4391-b520-1fccc0e7d6ca
tag.magic=1b70fcca-0579-446a-90d1-075c9ce62309
tag.meditation=59b9c259-62c3-4a1a-89d4-4a6f1070deb9
tag.mindfulness=9801169b-afa4-4785-890e-53911955e4d7
tag.mealprep=3ce58361-f147-441d-a7c9-e98e3e916a39
tag.movement=73645e21-02ae-4f39-bfb1-8dac623927ef
tag.musictalk=85d2fb8f-7257-4e08-8065-6161fa3029fa
tag.musicevents=c5247b10-deec-4d7a-84a5-db6a75cb5908
tag.news=77017b7b-6b98-4f0d-bd39-3ba96b66ec7a
tag.outdoors=89e105c9-2c45-42a9-a5f0-fc1ea6e7ba8b
tag.practice=04b4aaaa-c410-4c2e-9beb-da3896fc7d22
tag.reading=bd6fc011-575a-43f0-8418-9f912a295362
tag.retro=e027fb8b-219e-4959-8240-a4a082be0316
tag.robotics=56257f86-a66c-4ce8-af6d-89e9b1f13fed
tag.safespace=3575df89-da01-4fc1-939c-b5465093ed04
tag.spirituality=63f8ee17-1678-41ee-906a-8c55c3ce81df
tag.strength=07a1b526-3725-4ba5-8c53-efaad4941fb9
tag.surfing=8e44481a-4bc4-4155-b362-9bb499c15d3e
tag.tradart=5ec52c4f-a055-404c-82fe-ea98c74c7fe6
tag.travel=a6ff589a-33e5-4caf-8286-29dea98fc2e2
tag.tutorial=dc709206-c072-4340-a706-694578574c7e
tag.twitchcon=f317a85e-495e-4aee-a0d2-0720bd00a6ce
tag.usa=79713d37-6d2e-4953-b55b-8f47bb9caf72
tag.vectorart=f0ab2b07-14ed-4429-8ea3-3d7d400a50cd
tag.viewerlevels=fec05015-e841-4cff-a53c-8aa1336cf863
tag.warmingup=2920fbf2-293e-4753-8ec7-b69dba5392d0
tag.wargame=dbe20395-0e44-4156-92de-4a77f6cdccf0
tag.worldbuild=218c5e0e-e3a9-4fab-9ad5-994717d226fd
tag.easy=1eea2343-ca8e-4606-ab21-5c64e129f6db
tag.hard=ba2c968b-867a-49ce-aebc-3d978a204f4a
tag.beginners=ad18ee82-c0b2-46d4-b4f9-d45994443bd7
tag.casuals=cc8d5abb-39c9-4942-a1ee-e1558512119e
tag.allbosses=860f0dc1-5d6b-4504-a3e2-eca15a1cb816
tag.epic=df262ff6-74d1-415b-942c-d584d44426c4
mode.away.emoji=🐟 
mode.away.name=away
mode.away.status=fishies and music
mode.away.flags=music|visual
mode.away.category=272263131
mode.away.tags=linux,animation
mode.break.emoji=💤
mode.break.name=break
mode.break.status=taking a break (< 30 minutes)
mode.break.flags=music | visual
mode.break.category=same
mode.break.tags=
mode.yoga.emoji=🧘
mode.yoga.name=yoga
mode.yoga.status=ashtanga yoga asana (mysore style)
mode.yoga.flags=cam | mic | music | chat | focused
mode.yoga.category=509671
mode.yoga.tags=
mode.run.emoji=🏃
mode.run.name=run
mode.run.status=out running
mode.run.flags=cam | mic | chat | ama | out
mode.run.category=509658
mode.run.tags=
mode.skate.emoji=🛹
mode.skate.name=skate
mode.skate.status=out long-boarding
mode.skate.flags=cam | mic | chat | ama | out
mode.skate.category=509658
mode.skate.tags=
mode.bike.emoji=🚴
mode.bike.name=bike
mode.bike.status=out cycling
mode.bike.flags=cam | mic | chat | ama | out
mode.bike.category=509658
mode.bike.tags=
mode.work.emoji=🏢
mode.work.name=work
mode.work.status=kubernetes coworking
mode.work.flags=cam | mic | chat | focused | music | muted
mode.work.category=null
mode.work.tags=co-working
mode.code.emoji=💢
mode.code.name=code
mode.code.status=bash, go, c, or web
mode.code.flags=cam | mic | chat | topical | music
mode.code.category=null
mode.code.tags=programming
mode.hack.emoji=🥷
mode.hack.name=hack
mode.hack.status=hacking to learn
mode.hack.flags=cam | mic | chat | ama | music
mode.hack.category=null
mode.hack.tags=
mode.write.emoji=⌨️
mode.write.name=write
mode.write.status=writing
mode.write.flags=cam | mic | chat | focused | topical | music
mode.write.category=509658
mode.write.tags=
mode.rant.emoji=🤬
mode.rant.name=rant
mode.rant.status=ranting
mode.rant.flags=cam | mic | chat | focused | topical | music
mode.rant.category=509658
mode.rant.tags=evil
mode.clean.emoji=😐
mode.clean.name=clean
mode.clean.status=cleaning lab/studio
mode.clean.flags=cam | mic | chat | music | ama
mode.clean.category=509658
mode.clean.tags=
mode.dota2.emoji=⚔️
mode.dota2.name=dota2
mode.dota2.status=crystal, legion, chant, np, *ama chat*
mode.dota2.flags=
mode.dota2.category=null
mode.dota2.tags=
mode.witcher3.emoji=🐺
mode.witcher3.name=witcher3
mode.witcher3.status=cat school, triss line, *ama chat*
mode.witcher3.flags=
mode.witcher3.category=null
mode.witcher3.tags=
mode.shenzen.emoji=🔢
mode.shenzen.name=shenzen
mode.shenzen.status=learning assembly-ish, *ama chat*
mode.shenzen.flags=
mode.shenzen.category=null
mode.shenzen.tags=
mode.tf2.emoji=🏹
mode.tf2.name=tf2
mode.tf2.status=bow sniper, engie, pyro, *ama chat*
mode.tf2.flags=
mode.tf2.category=null
mode.tf2.tags=
mode.learn.emoji=🤯
mode.learn.name=learn
mode.learn.status=colearning, *topic chat* to help
mode.learn.flags=
mode.learn.category=null
mode.learn.tags=
mode.party.emoji=🎉
mode.party.name=party
mode.party.status=music, dancing, drinking, *ama chat*
mode.party.flags=
mode.party.category=509658
mode.party.tags=
mode.jaunt.emoji=🌤️
mode.jaunt.name=jaunt
mode.jaunt.status=walk/talk, tours, adventures, *ama chat*
mode.jaunt.flags=
mode.jaunt.category=509658
mode.jaunt.tags=
mode.art.emoji=🎨
mode.art.name=art
mode.art.status=galleries, crawls, interviews, *topic chat*
mode.art.flags=
mode.art.category=509660
mode.art.tags=
mode.music.emoji=🎵
mode.music.name=music
mode.music.status=live music, pubs, *ama chat*
mode.music.flags=
mode.music.category=26936
mode.music.tags=
mode.course.emoji=⚡
mode.course.name=course
mode.course.status=instructional content, *topic chat*
mode.course.flags=
mode.course.category=null
mode.course.tags=
mode.morning.emoji=☕
mode.morning.name=morning
mode.morning.status=cozy, wake-up, plan, news, *ama chat*
mode.morning.flags=
mode.morning.category=509658
mode.morning.tags=
mode.talk.emoji=☎️
mode.talk.name=talk
mode.talk.status=invited guests in discord, *topic ama*
mode.talk.flags=
mode.talk.category=417752
mode.talk.tags=
mode.hang.emoji=🍻
mode.hang.name=hang
mode.hang.status=discord lobby, members only, *ama chat*
mode.hang.flags=
mode.hang.category=509658
mode.hang.tags=
mode.record.emoji=🎬
mode.record.name=record
mode.record.status=make specific youtube videos, *no chat*
mode.record.flags=
mode.record.category=null
mode.record.tags=
